name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Resume
        run: make pdf

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: |
            **.pdf

