name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/typst/typst:latest
    strategy:
      matrix:
        pdf:
        - resume.pdf
        - Elijah Caine M. Voigt resume.pdf
        - Elijah Caine McDade Voigt resume.pdf
        - Elijah Voigt resume.pdf

    steps:
      - uses: actions/checkout@v4

      - name: Install fonts
        run: |
          apk -U add ttf-freefont

      - name: Build Resume
        run: |
          typst compile resume.typ '${{ matrix.pdf }}'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: '${{ matrix.pdf }}'
          path: '${{ matrix.pdf }}'


